# XcodeGen configuration
# This file tells XcodeGen how to generate the Xcode project

name: DopetracksApp
options:
  bundleIdPrefix: com.dopetracks
  deploymentTarget:
    macOS: "12.0"
  developmentLanguage: en

targets:
  DopetracksApp:
    type: application
    platform: macOS
    sources:
      - path: DopetracksApp
        excludes:
          - "**/*.xcassets"
          - "**/Info.plist"
    resources:
      - path: DopetracksApp/DopetracksApp/Assets.xcassets
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.dopetracks.app
      PRODUCT_NAME: DopetracksApp
      MACOSX_DEPLOYMENT_TARGET: "12.0"
      SWIFT_VERSION: "5.9"
    info:
      path: DopetracksApp/DopetracksApp/Info.plist
      properties:
        CFBundleName: DopetracksApp
        CFBundleDisplayName: Dopetracks
        CFBundleIdentifier: com.dopetracks.app
        CFBundleVersion: "1.0.0"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        LSMinimumSystemVersion: "12.0"
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        NSFullDiskAccessUsageDescription: "Dopetracks needs Full Disk Access to read your Messages database and create Spotify playlists from shared songs."

